---
- name: Create and Launch a Job template for an I generated playbook
  hosts: all
  gather_facts: false
  environment:
    GATEWAY_USERNAME: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
    GATEWAY_PASSWORD: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
    GATEWAY_HOSTNAME: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
    GATEWAY_VERIFY_SSL: "{{ lookup('ansible.builtin.env', 'CONTROLLER_VERIFY_SSL') }}"
    SN_HOST: "https://{{ snow_instance }}.service-now.com"
    SN_USERNAME: "{{ snow_username }}"
    SN_PASSWORD: "{{ snow_password }}"
  pre_tasks:
    - name: Authenticate with platform gateway
      ansible.platform.token:
        description: Create token
        scope: write
        state: present
      register: r_authtoken

    - name: Set fact for token
      ansible.builtin.set_fact:
        controller_oauthtoken: “{{ r_authtoken.ansible_facts.aap_token.token }}”
  tasks:
  - name: Retrieve all incidents that contain SAP in its short description by using field query
    servicenow.itsm.incident_info:
      query:
        - short_description: = Services API is Down
        - state: = new
        - caller: = ansible
    register: snow_incidents
  
  - name: set the fact for the incident number
    ansible.builtin.set_fact:
      snow_incident: "{{ snow_incidents.records | sort(attribute='number') | last }}"

  - name: Add project
    ansible.controller.project:
      name: "AI Generated Playbooks"
      description: "Playbooks generated by Lightspeed"
      organization: "{{ input_organization | default('Foxhound') }}"
      scm_type: git
      scm_url: "{{ input_git_repo | default('https://github.com/raedrizk/ansible_ai_generated_playbooks.git') }}"
      scm_branch: "{{ input_git_branch | default('main') }}"
      update_project: true
      state: present

  - name: Create job template from the generated playbook
    ansible.controller.job_template:
      name: "BOT_AI_Generated_Playbook"
      job_type: "run"
      organization: "{{ input_organization | default('Foxhound') }}"
      inventory: "{{ input_inventory | default('Foxhound Inventory') }}"
      limit: "{{ input_limit | default('api.foxhound.unit') }}"
      project: "AI Generated Playbooks"
      playbook: "{{ generated_playbook_name | default('generated_playbook.yml') }}"
      execution_environment: "{{ input_execution_environment | default('foxhound-complete-ee') }}"
      credentials:
        - "{{ input_credential | default('foxhound-lab-admin') }}"
      state: present

  - name: Create a workflow job template with workflow nodes in template
    ansible.controller.workflow_job_template:
      name: WF_AIDemo_run_ai_generated_playbook
      description: "Workflow job template to apply AI generated playbook"
      organization: "{{ input_organization | default('Foxhound') }}"
      ask_variables_on_launch: true
      extra_vars:  
        snow_incident_number: "{{ snow_incident.number }}"

  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: snow_close_incident
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: ServiceNowDemo_snow_close_Incident
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        snow_incident_close_notes: "Issue Resolved by Ansible"

  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: snow_update_fail2
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: ServiceNowDemo_snow_update_Incident
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        snow_update_comments: "Validating service endpoint Failed"   
  
  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: snow_update_success2
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: ServiceNowDemo_snow_update_Incident
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        snow_update_comments: "Validating service endpoint Succeseeded"
      success_nodes:
        - snow_close_incident   
  
  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: slack_update_fail2
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: AIDemo_slack_post_message
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        slack_message: "Validating service endpoint Failed"
        slack_message_color: "danger"

  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: slack_update_success2
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: AIDemo_slack_post_message
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        slack_message: "Validating service endpoint Succeseeded"
        slack_message_color: "good"

  - name: Create parent node for prior nodes
    ansible.controller.workflow_job_template_node:
      identifier: validate_service_endpoint
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: LinuxDemo_linux_validate_local_endpoint
      organization: "{{ input_organization | default('Foxhound') }}"
      success_nodes:
        - slack_update_success2
        - snow_update_success2
      failure_nodes:
        - slack_update_fail2
        - snow_update_fail2

  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: snow_update_fail
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: ServiceNowDemo_snow_update_Incident
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        snow_update_comments: "Running AI generated playbook Failed"   
  
  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: snow_update_success
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: ServiceNowDemo_snow_update_Incident
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        snow_update_comments: "Running AI generated playbook Succeseeded"  
      always_nodes:
        - validate_service_endpoint 
  
  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: slack_update_fail
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: AIDemo_slack_post_message
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        slack_message: "Running AI generated playbook Failed"
        slack_message_color: "danger"

  - name: Create WorkFlow job template nodes
    ansible.controller.workflow_job_template_node:
      identifier: slack_update_success
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: AIDemo_slack_post_message
      organization: "{{ input_organization | default('Foxhound') }}"
      extra_data:
        slack_message: "Running AI generated playbook Succeseeded"
        slack_message_color: "good"
      always_nodes:
        - validate_service_endpoint 
        
  - name: Create parent node for prior nodes
    ansible.controller.workflow_job_template_node:
      identifier: run_ai_generated_playbook
      workflow: WF_AIDemo_run_ai_generated_playbook
      unified_job_template: BOT_AI_Generated_Playbook
      organization: "{{ input_organization | default('Foxhound') }}"
      success_nodes:
        - slack_update_success
        - snow_update_success
      failure_nodes:
        - slack_update_fail
        - snow_update_fail

