---
- name: Create and Launch a Job template for an I generated playbook
  hosts: all
  gather_facts: false
  environment:
    CONTROLLER_USERNAME: "{{ controller_username }}"
    CONTROLLER_PASSWORD: "{{ controller_password }}"
    CONTROLLER_HOST: "{{ controller_hostname }}"
    CONTROLLER_VERIFY_SSL: "{{ controller_verify_ssl }}"
    GATEWAY_USERNAME: "{{ controller_username }}"
    GATEWAY_PASSWORD: "{{ controller_password }}"
    GATEWAY_HOSTNAME: "{{ controller_hostname }}"
    GATEWAY_VERIFY_SSL: "{{ controller_verify_ssl }}"
  pre_tasks:
    - name: Authenticate with platform gateway
      ansible.platform.token:
        description: Create token
        scope: write
        state: present
      register: r_authtoken

    - name: Set fact for token
      ansible.builtin.set_fact:
        controller_oauthtoken: “{{ r_authtoken.ansible_facts.aap_token.token }}”
  tasks:
  - name: Add project
    ansible.controller.project:
      name: "AI Generated Playbooks"
      description: "Playbooks generated by Lightspeed"
      organization: "{{ input_organization | default('Foxhound') }}"
      scm_type: git
      scm_url: "{{ input_git_repo | default('https://github.com/raedrizk/ansible_ai_generated_playbooks.git') }}"
      scm_branch: "{{ input_git_branch | default('main') }}"
      update_project: true
      state: present

  - name: Create job template from the generated playbook
    ansible.controller.job_template:
      name: "AI Generated Playbook"
      job_type: "run"
      organization: "{{ input_organization | default('Foxhound') }}"
      inventory: "{{ input_inventory | default('Foxhound Inventory') }}"
      limit: "{{ input_limit | default('api.foxhound.unit') }}"
      project: "AI Generated Playbooks"
      playbook: "{{ generated_playbook_name | default('generated_playbook.yml') }}"
      become_enabled: true
      credentials:
        - "{{ input_credential | default('foxhound-lab-admin') }}"
        - "{{ input_credential_2 | default(omit) }}"
        - "{{ input_credential_3 | default(omit) }}"
      state: present



