---
- name: Prompt Lightspeed and get back an answer
  ansible.builtin.uri:
    url: "{{ ai_host }}:{{ ai_port }}/{{ ai_endpoint }}"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ ai_token }}"
    body_format: json
    body:
      text: "{{ ai_prompt }}"
  register: response

- name: Print response
  ansible.builtin.debug:
    msg: "{{ response.json.playbook }}"
  when: response.status == 200

- name: Set stats for following Jobs
  ansible.builtin.set_stats:
    data:
      lightspeed_response: "{{ response.json.playbook }}"
  when: response.status == 200

- name: Set fact for following tasks
  ansible.builtin.set_fact:
    lightspeed_response: "{{ response.json.playbook }}"
  when: response.status == 200

- name: Write the generated playbook to a file and add to git if needed
  ansible.builtin.include_tasks: add_to_git.yml
  when: add_to_scm
