---
- name: Prompt Lightspeed and get back an answer
  ansible.builtin.uri:
    url: "{{ lightspeed_endpoint }}"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ lightspeed_token }}"
    body_format: json
    body:
      text: "{{ lightspeed_prompt }}"
  register: response

- name: Print response
  ansible.builtin.debug:
    msg: "{{ response.json.playbook }}"
  when: response.status == 200

- name: Set stats for following Jobs
  ansible.builtin.set_stats:
    data:
      lightspeed_response: "{{ response.json.playbook }}"
  when: response.status == 200

# - name: write playbook to file
#   ansible.builtin.copy:
#     content: "{{ response.json.playbook }}"
#     dest: /tmp/lightspeed_playbook_test.yml
#   when: response.status == 200
