---
lightspeed_endpoint: "{{ input_lightspeed_endpoint | default('https://c.ai.ansible.redhat.com/api/v1/ai/generations/playbook/') }}"
lightspeed_token: "{{ input_lightspeed_token | default('mysupersecrettoken') }}"
lightspeed_prompt: "{{ input_lightspeed_prompt | default('install and start httpd on all hosts in the web group, all of which are running RHEL8') }}"

