---
ai_host: "{{ input_ai_host | default('https://c.ai.ansible.redhat.com') }}"
ai_port: "{{ input_ai_port | default(443) }}"
ai_endpoint: "{{ input_ai_endpoint | default('api/v1/ai/generations/playbook/') }}"
ai_token: "{{ input_ai_token | default('mysupersecrettoken') }}"
ai_prompt: "{{ input_ai_prompt | default('install and start httpd on all hosts in the web group, all of which are running RHEL8') }}"
