---
- name: Listen for ServiceNow events sent from the Event-Driven Ansible Notification Service
  hosts: localhost
  ## Listening on localhost port 5000.
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: NEW SNOW Incident - API Down
      condition: event.payload is defined and event.payload.short_description contains "Services API is Down"
      action:
        run_workflow_template:
          name: WF_AIDemo_Enhance_Incident_and_Notify_slack
          organization: "{{ job_templates_org_name | default('Foxhound') }}"
          job_args:
            extra_vars:
              snow_incident_number: "{{ event.payload.number }}"
