---
- name: Listen for ServiceNow events sent from the Event-Driven Ansible Notification Service
  hosts: localhost
  ## Listening on localhost port 5000.
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: SNOW Condition - API Down
      condition: event.payload is defined and event.payload.short_description contains "NodeJS API Down"
      action:
        run_workflow_template:
          name: WF_EDADemo_action_start_srevice_and_close_incident
          organization: "{{ job_templates_org_name | default('Foxhound') }}"
          job_args:
            extra_vars:
              snow_incident_number: "{{ event.payload.number }}"
