---
- name: Listen for ServiceNow events sent from the Event-Driven Ansible Notification Service
  hosts: localhost
  sources:
    - name: Watch for new incidents
      servicenow.itsm.records:
        table: incident
        interval: 5
  rules:
    - name: NEW SNOW Incident - API Down
      # condition: event.payload is defined and event.payload.short_description contains "Services API is Down"
      condition: event.sys_class_name == 'incident' and event.reassignment_count == '0' and  event.reopen_count == '0'
                 and event.sys_mod_count == '0' and event.state == '1' and event.sys_created_by == 'ansible'
                 and event.short_description is defined and event.short_description contains "Services API is Down"
      action:
        run_workflow_template:
          name: WF_AIDemo_Enhance_Incident_and_Notify_slack
          organization: "{{ job_templates_org_name | default('Foxhound') }}"
          job_args:
            extra_vars:
              snow_incident_number: "{{ event.number }}"

    - name: Catch all other events
      condition: event.sys_id is defined
      action:
        print_event:
          pretty: true
