---
- name: Check the health of Services API
  hosts: localhost
  execution_strategy: sequential
  sources:
    - name: check web server
      ansible.eda.url_check:
        urls:
          - "{{ api_url }}"
        delay: "{{ url_check_delay | default(30) }}"
  rules:
    - name: Service down
      condition: event.url_check.status == 'down'
      actions:
        # - run_job_template:
        #     name: ServiceNowDemo_snow_create_Incident
        #     organization: "{{ job_templates_org_name | default('Foxhound') }}"
        #     set_facts: true
        #     job_args:
        #       extra_vars:
        #         snow_caller_choice: rsoliman
        #         snow_cr_short_desc_choice: Services API is Down
        #         snow_inc_desc_choice: A routine check of the NodeJS Services API has failed.
        #         snow_inc_urgency: high
        #         snow_inc_impact: high
        - run_job_template:
            name: AIDemo_slack_post_message
            organization: "{{ job_templates_org_name | default('Foxhound') }}"
            set_facts: true
            job_args:
              extra_vars:
                slack_message: "!!! Services API is Down !!!1"
                slack_message_color: "danger"
        - run_job_template:
            name: AIDemo_slack_post_message
            organization: "{{ job_templates_org_name | default('Foxhound') }}"
            set_facts: true
            job_args:
              extra_vars:
                slack_message: "!!! Services API is Down !!!2"
                slack_message_color: "danger"
