---
ai_host: "{{ input_ai_host | default('http://127.0.0.1') }}"
ai_port: "{{ input_ai_port | default(11434) }}"
ai_endpoint: "{{ input_ai_endpoint | default('v1/chat/completions') }}"
ai_validate_certs: "{{ input_ai_validate_certs | default(false) }}"
ai_token: "{{ input_ai_token | default('mysupersecrettoken') }}"
ai_model: "{{ input_ai_model | default('granite3.3:latest') }}"
ai_max_tokens: "{{ input_ai_max_tokens | default(500) }}"
ai_temperature: "{{ input_ai_temperature | default(0.7) }}"
ai_prompt: "{{ input_ai_prompt | default('Who is the protagonist in Metal Gear Solid 3: Snake Eater?') }}"

